#!/usr/bin/env bash

#previous content
mkdir /tmp/tutorial
cd /tmp/tutorial
mkdir dir1 dir2 dir3
touch cat dog

#current contnet
ls ~ | wc -l

#note
#the pip does not create an output file like wc. Reminder, ~ is used to address files or directories in the users home 
