#!/usr/bin/env bash

#previous content
mkdir /tmp/tutorial
cd /tmp/tutorial
echo "this has words in it" > combined.txt


#lesson content
echo "Number of unique lines"
cat combined.txt | uniq | wc -l

