#!/usr/bin/env bash

#previous content
mkdir /tmp/tutorial
cd /tmp/tutorial
echo "this has words in it" > combined.txt

#lesson content
sudo apt install tree

cd /tmp/tutorial
tree

# putting udo in front of any command runs it as a superuser
